version: '3.8'

services:
  radio-bot:
    build: .
    container_name: discord-radio-bot
    restart: always
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - STREAM_URL=${STREAM_URL}
      - FFMPEG_PATH=ffmpeg
